name: workday_noir
description: A premium offline-first personal workday tracker.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  intl: ^0.20.2
  share_plus: ^11.0.0
  flutter_local_notifications: ^19.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
