import 'package:flutter/cupertino.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import '../../core/date_utils.dart';
import '../../data/models/work_entry.dart';
import '../../data/repositories/workday_repository.dart';
import '../../shared/widgets/noir_card.dart';

class CalendarScreen extends ConsumerStatefulWidget { const CalendarScreen({super.key}); @override ConsumerState<CalendarScreen> createState()=>_CalendarState(); }
class _CalendarState extends ConsumerState<CalendarScreen> { DateTime month = DateTime(todayLocal().year,todayLocal().month); @override Widget build(BuildContext context){ final entries=ref.watch(entriesProvider); return CupertinoPageScaffold(navigationBar: const CupertinoNavigationBar(largeTitle: Text('Calendar'),automaticallyImplyLeading:false),child: SafeArea(child: entries.when(loading:()=>const Center(child:CupertinoActivityIndicator()),error:(_,__)=>const Center(child:Text('Something went wrong.')),data:(all)=>ListView(padding:const EdgeInsets.all(20),children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[CupertinoButton(padding:EdgeInsets.zero,onPressed:()=>setState(()=>month=DateTime(month.year,month.month-1)),child:const Icon(CupertinoIcons.chevron_left)),Text(DateFormat('MMMM yyyy').format(month),style:const TextStyle(fontSize:20,fontWeight:FontWeight.w700)),CupertinoButton(padding:EdgeInsets.zero,onPressed:month.isBefore(DateTime(todayLocal().year,todayLocal().month))?()=>setState(()=>month=DateTime(month.year,month.month+1)):null,child:const Icon(CupertinoIcons.chevron_right))]),const SizedBox(height:18),_CalendarGrid(month:month,entries:all),const SizedBox(height:24),const Text('Tap a previous day to edit its status.',style:TextStyle(color:CupertinoColors.systemGrey)),])))); } }
class _CalendarGrid extends StatelessWidget { final DateTime month; final List<WorkEntry> entries; const _CalendarGrid({required this.month,required this.entries}); @override Widget build(BuildContext context){ final map={for(final e in entries)e.date:e}; final first=DateTime(month.year,month.month,1); final days=DateTime(month.year,month.month+1,0).day; final offset=(first.weekday-1); final cells=<Widget>[]; for(int i=0;i<offset;i++)cells.add(const SizedBox()); for(int d=1;d<=days;d++){final date=DateTime(month.year,month.month,d); final e=map[dateKey(date)]; final future=date.isAfter(todayLocal()); cells.add(GestureDetector(onTap:future?null:()=>_edit(context,date,e),child:Container(margin:const EdgeInsets.all(3),height:48,decoration:BoxDecoration(color:e==null?const Color(0xFF121215):const Color(0xFF1D1D21),borderRadius:BorderRadius.circular(13),border:Border.all(color:dateKey(date)==dateKey(todayLocal())?const Color(0x99FFFFFF):const Color(0x10FFFFFF))),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text('$d',style:TextStyle(color:future?CupertinoColors.systemGrey4:CupertinoColors.white)),if(e!=null)Icon(e.status==WorkStatus.worked?CupertinoIcons.check_mark:CupertinoIcons.xmark,size:12,color:CupertinoColors.systemGrey)])))); } return GridView.count(crossAxisCount:7,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),children:[for(final x in ['M','T','W','T','F','S','S'])Center(child:Text(x,style:const TextStyle(color:CupertinoColors.systemGrey,fontSize:12))),...cells]); }
Future<void> _edit(BuildContext context,DateTime date,WorkEntry? entry) async { if(!context.mounted)return; showCupertinoModalPopup(context:context,builder:(_)=>CupertinoActionSheet(title:Text(DateFormat('MMMM d, yyyy').format(date)),actions:[CupertinoActionSheetAction(onPressed:(){Navigator.pop(context);},child:Text('Worked ${entry?.status==WorkStatus.worked?'✓':''}')),CupertinoActionSheetAction(onPressed:(){Navigator.pop(context);},child:Text("Didn't work ${entry?.status==WorkStatus.didNotWork?'×':''}"))],cancelButton:CupertinoActionSheetAction(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')))); }
}
