import 'package:flutter/cupertino.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../data/repositories/workday_repository.dart';

class SettingsScreen extends ConsumerWidget { const SettingsScreen({super.key}); @override Widget build(BuildContext context,WidgetRef ref)=>CupertinoPageScaffold(navigationBar:const CupertinoNavigationBar(largeTitle:Text('Settings'),automaticallyImplyLeading:false),child:SafeArea(child:ListView(padding:const EdgeInsets.all(20),children:[_Section(children:[CupertinoListTile(title:const Text('Appearance'),leading:const Icon(CupertinoIcons.moon),trailing:const Icon(CupertinoIcons.chevron_right),onTap:()=>showCupertinoModalPopup(context:context,builder:(_)=>CupertinoActionSheet(title:const Text('Appearance'),actions:[CupertinoActionSheetAction(onPressed:()=>Navigator.pop(context),child:const Text('Noir')),CupertinoActionSheetAction(onPressed:()=>Navigator.pop(context),child:const Text('System')),CupertinoActionSheetAction(onPressed:()=>Navigator.pop(context),child:const Text('Light'))],cancelButton:CupertinoActionSheetAction(onPressed:()=>Navigator.pop(context),child:const Text('Cancel'))))),CupertinoListTile(title:const Text('Daily Reminder'),leading:const Icon(CupertinoIcons.bell),trailing:const Icon(CupertinoIcons.chevron_right),onTap:()=>_coming(context)),CupertinoListTile(title:const Text('Export'),leading:const Icon(CupertinoIcons.square_arrow_up),trailing:const Icon(CupertinoIcons.chevron_right),onTap:()=>_coming(context))]),const SizedBox(height:24),_Section(children:[CupertinoListTile(title:const Text('Delete All Data',style:TextStyle(color:CupertinoColors.systemRed)),leading:const Icon(CupertinoIcons.trash,color:CupertinoColors.systemRed),onTap:()=>_delete(context,ref)]),const SizedBox(height:20),const Center(child:Text('Workday Noir · 1.0.0',style:TextStyle(color:CupertinoColors.systemGrey,fontSize:12))) ])));}
Future<void> _delete(BuildContext context,WidgetRef ref)async{final ok=await showCupertinoDialog<bool>(context:context,builder:(_)=>CupertinoAlertDialog(title:const Text('Delete all work history?'),content:const Text('This action cannot be undone.'),actions:[CupertinoDialogAction(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancel')),CupertinoDialogAction(isDestructiveAction:true,onPressed:()=>Navigator.pop(context,true),child:const Text('Delete Everything'))]));if(ok==true){await ref.read(repositoryProvider).deleteAll();ref.invalidate(entriesProvider);ref.invalidate(todayEntryProvider);}}
void _coming(BuildContext context)=>showCupertinoDialog(context:context,builder:(_)=>const CupertinoAlertDialog(title:Text('Coming next'),content:Text('This foundation is ready for the native iOS integration layer.'),actions:[CupertinoDialogAction(child:Text('OK'))]));
}
class _Section extends StatelessWidget{final List<Widget> children;const _Section({required this.children});@override Widget build(BuildContext context)=>Container(decoration:BoxDecoration(color:const Color(0xFF131316),borderRadius:BorderRadius.circular(18)),child:Column(children:children));}
